version: '3'

services:
  cuda-dev:
    build: .
    security_opt: # options needed for gdb debugging
      - seccomp:unconfined
      - apparmor:unconfined
    container_name: doodle
#    entrypoint to start ssh service and sleep to keep container running
    entrypoint: /bin/bash -c "service ssh start && sleep infinity"
    ports:
      - "7776:22"
      - "7777:7777"
    volumes:
      - /data1/projects/cuda_by_example:/workspace/cuda_by_example
      - /data1/projects/cuda-samples:/workspace/cuda-samples